### ISSUE TITLE
Add Angular 8 compatibility

### ISSUE THREAD

**Issue by nikolayr1** [Teradata/covalent#1390]
### Feature Request
Please make @covalent/core compatible with Angular 8

#### What is the expected behavior?
Covalent package works fine in Angular 8 project.

#### What is the motivation / use case for changing the behavior?
Angular 8 features

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Angular 8 

##### Other information
This error happening after angular 7.2 -> angular 8.0 migration. ("@covalent/core": "^2.0.1" is used)
![image](https://user-images.githubusercontent.com/11279857/58546716-9f94e880-820e-11e9-9bdb-e83b3c07bdda.png)

**Comment by dlq84** [comment]
It was removed in this commit after being deprecated for a while: https://github.com/angular/angular/commit/3a9d2473ca1b5a5ef7595bcb58fb52b1677be76f#diff-247c56c4fdd0f71feca2f9373ba0980a

It now exists ins `@angular/common` instead: https://github.com/angular/angular/commit/2a7ebbe982624c7cc617670f6f0284780de2d55d#diff-4410d13f4f850d652fed4180f23f7618

**Comment by dlq84** [comment]
I have a branch that should fix this issue, want me to do a PR?

**Comment by nikolayr1** [comment]
@dlq84 yes, of course)

**Comment by DaSchTour** [comment]
Wow. That's a real deal breaker. I wonder why this wasn't fixed many versions ago. It's deprecated since two years.

**Comment by dlq84** [comment]
> Wow. That's a real deal breaker. I wonder why this wasn't fixed many versions ago. It's deprecated since two years.

Let's hope it doesn't take another two years to merge my PR ;)

**Comment by jaa1982** [comment]
Hi @emoralesb05 , any comment on this one ?  Lot of us out here eager for an upgrade to angular@8 , and this seems to be the only blocker .  @dlq84 's pending PR should give us a quick fix

**Comment by shadow1349** [comment]
I would also really like to see Angular 8 compatibility!

**Comment by kcprabase** [comment]
Any update on this when will update be available for angular 8 compatibility

**Comment by jeremylcarter** [comment]
We are looking forward to upgrading to Angular 8. Would be great if this was tested and merged ASAP to ensure we can all upgrade our apps. Thank you!

**Comment by rubandangol** [comment]
We're also waiting for the Angular 8 compatible update. This is this only thing blocking us from upgrading to Angular 8.
